const fs = require('fs');
const FILE = 'index.html';
let src = fs.readFileSync(FILE, 'utf8');
let fails = 0;

function replaceExact(from, to, desc) {
  const count = src.split(from).length - 1;
  if (count === 0) { console.error('MISS: ' + desc); fails++; return; }
  if (count > 1) { console.error('AMBIGUOUS (' + count + '): ' + desc); fails++; return; }
  src = src.replace(from, to);
  console.log('OK: ' + desc);
}

const N = '\r\n';

// PATCH 1: Add ExcelJS CDN
replaceExact(
  '<script src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>',
  '<script src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>' + N +
  '<script src="https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js"></script>',
  'PATCH 1: Add ExcelJS CDN'
);

// PATCH 2: Change wb creation inside exportBatchExcel to ExcelJS Workbook
replaceExact(
  "  const wb = XLSX.utils.book_new();" + N +
  "  // Build REKAP rows and index data for per-unit sheets and TRANSFER",
  "  const wb = new ExcelJS.Workbook();" + N +
  "  // Build REKAP rows and index data for per-unit sheets and TRANSFER",
  'PATCH 2: Switch exportBatchExcel wb to ExcelJS.Workbook'
);

// PATCH 3: Replace SheetJS output section with ExcelJS output section
// From: lines 6228-6344 (// Shared style helpers ... showToast + closing })
const fromOutput = [
  "  // Shared style helpers",
  "  var _xt = { style: 'thin', color: { rgb: '000000' } };",
  "  var _xb = { top: _xt, bottom: _xt, left: _xt, right: _xt };",
  "  var _xh = { font: { bold: true, italic: true }, fill: { fgColor: { rgb: 'FFFF00' }, patternType: 'solid' }, border: _xb };",
  "  function _xcs(ws, r, c, s) { var ref = XLSX.utils.encode_cell({ r: r, c: c }); if (!ws[ref]) ws[ref] = { t: 's', v: '' }; ws[ref].s = s; }",
  "  function _xnf(ws, r, c) { var ref = XLSX.utils.encode_cell({ r: r, c: c }); if (ws[ref] && ws[ref].t === 'n') { var _v = ws[ref].v; ws[ref].t = 's'; ws[ref].v = Math.round(_v).toLocaleString('id'); delete ws[ref].w; } }",
  "  // REKAP — shift TOTAL to col M; apply header style + numFmt",
  "  var rekapAoa = rekapRows.map(function(row) { var r2 = row.slice(0, 11); r2.push(''); r2.push(row.length > 11 ? row[11] : ''); return r2; });",
  "  var wsRekap = XLSX.utils.aoa_to_sheet(rekapAoa);",
  "  var rkR = XLSX.utils.decode_range(wsRekap['!ref']);",
  "  for (var ci = 0; ci <= 12; ci++) _xcs(wsRekap, 0, ci, _xh);",
  "  for (var ri = 1; ri <= rkR.e.r; ri++) { _xnf(wsRekap, ri, 8); _xnf(wsRekap, ri, 10); _xnf(wsRekap, ri, 12); }",
  "  XLSX.utils.book_append_sheet(wb, wsRekap, 'REKAP');",
  "  // SLIP GAJI — per-operator: Stockpile / Kapal split + Basis + Kasbon",
  "  var _xsec = { font: { bold: true }, fill: { fgColor: { rgb: 'E2EFDA' }, patternType: 'solid' }, border: _xb };",
  "  var _xtot = { font: { bold: true }, fill: { fgColor: { rgb: 'DBEAFE' }, patternType: 'solid' }, border: _xb };",
  "  var _xsub = { font: { italic: true }, border: _xb };",
  "  var _gpok = batchType === 'end_of_month' ? 3100000 : 0;",
  "  var slipRows = [];",
  "  var _xnfAmt = function(ws, ri, ci) {",
  "    var ref = XLSX.utils.encode_cell({ r: ri, c: ci });",
  "    if (ws[ref] && ws[ref].t === 'n') { var _v = ws[ref].v; ws[ref].t = 's'; ws[ref].v = Math.round(_v).toLocaleString('id'); delete ws[ref].w; }",
  "  };",
  "  Object.keys(unitSheetData).sort().forEach(function(code) {",
  "    var entry = unitSheetData[code];",
  "    var kasbon = kasbonMap[entry.opName] || 0;",
  "    var stkRs = [], kapalRs = [];",
  "    entry.rows.forEach(function(r) {",
  "      if (typeof r[11] === 'number' && r[11] > 0) {",
  "        if (r[9] === 'STK') stkRs.push(r); else kapalRs.push(r);",
  "      }",
  "    });",
  "    var stkTotal = stkRs.reduce(function(s, r) { return s + r[11]; }, 0);",
  "    var kapalTotal = kapalRs.reduce(function(s, r) { return s + r[11]; }, 0);",
  "    var unitTotal = stkTotal + kapalTotal;",
  "    var grandTotal = unitTotal + _gpok - kasbon;",
  "    slipRows.push(['Unit:', code, '', 'Nama Operator:', entry.opName || code]);",
  "    slipRows.push(['Periode:', periodeStr, '', '', '']);",
  "    slipRows.push([]);",
  "    if (stkRs.length > 0) {",
  "      slipRows.push(['Pekerjaan Stockpile:', '', '', '', '']);",
  "      stkRs.forEach(function(r, i) {",
  "        slipRows.push(['', (i + 1) + '.', r[0] + '  (' + r[1] + ')', r[7] + ' jam', r[11]]);",
  "      });",
  "      slipRows.push(['', '', 'Subtotal Stockpile:', '', stkTotal]);",
  "      slipRows.push([]);",
  "    }",
  "    if (kapalRs.length > 0) {",
  "      slipRows.push(['Pekerjaan Kapal:', '', '', '', '']);",
  "      kapalRs.forEach(function(r, i) {",
  "        var kade = r[3] ? r[3] + '  ' : '';",
  "        slipRows.push(['', (i + 1) + '.', r[2], kade + '(' + r[1] + ')', r[11]]);",
  "      });",
  "      slipRows.push(['', '', 'Subtotal Kapal:', '', kapalTotal]);",
  "      slipRows.push([]);",
  "    }",
  "    slipRows.push(['', '', 'Total Kerja:', '', unitTotal]);",
  "    if (_gpok > 0) slipRows.push(['', '', 'Gaji Pokok (Basis):', '', _gpok]);",
  "    if (kasbon > 0) slipRows.push(['', '', 'Kasbon:', '', -kasbon]);",
  "    slipRows.push(['', '', 'TOTAL BERSIH:', '', grandTotal]);",
  "    slipRows.push([]);",
  "    slipRows.push([]);",
  "  });",
  "  var wsSlip = XLSX.utils.aoa_to_sheet(slipRows);",
  "  slipRows.forEach(function(row, ri) {",
  "    if (!row || row.length === 0) return;",
  "    var c0 = row[0], c2 = row[2];",
  "    if (c0 === 'Unit:' || c0 === 'Periode:') {",
  "      for (var ci = 0; ci < 5; ci++) _xcs(wsSlip, ri, ci, _xh);",
  "    } else if (c0 === 'Pekerjaan Stockpile:' || c0 === 'Pekerjaan Kapal:') {",
  "      for (var ci = 0; ci < 5; ci++) _xcs(wsSlip, ri, ci, _xsec);",
  "    } else if (c2 === 'Subtotal Stockpile:' || c2 === 'Subtotal Kapal:') {",
  "      _xcs(wsSlip, ri, 2, _xsub); _xcs(wsSlip, ri, 4, _xsub); _xnfAmt(wsSlip, ri, 4);",
  "    } else if (c2 === 'Total Kerja:' || c2 === 'Gaji Pokok (Basis):') {",
  "      _xcs(wsSlip, ri, 2, { font: { bold: true } }); _xnfAmt(wsSlip, ri, 4);",
  "    } else if (c2 === 'Kasbon:') {",
  "      _xcs(wsSlip, ri, 2, { font: { bold: true, color: { rgb: 'DC2626' } } }); _xnfAmt(wsSlip, ri, 4);",
  "    } else if (c2 === 'TOTAL BERSIH:') {",
  "      for (var ci = 0; ci < 5; ci++) _xcs(wsSlip, ri, ci, _xtot); _xnfAmt(wsSlip, ri, 4);",
  "    } else {",
  "      _xnfAmt(wsSlip, ri, 4);",
  "    }",
  "  });",
  "  XLSX.utils.book_append_sheet(wb, wsSlip, 'SLIP GAJI');",
  "  // TRANSFER sheet",
  "  const gajiPokok = batchType === 'end_of_month' ? 3100000 : 0;",
  "  const transferRows = [['No','Nama OP','Unit','Total Kerja','Gaji Pokok','Grand Total','Admin Fee','Net Transfer','Bank','No. Rekening','Nama Rekening']];",
  "  let no = 1;",
  "  let trTotKerja = 0, trTotPokok = 0, trTotGrand = 0, trTotFee = 0, trTotNet = 0;",
  "  Object.keys(opTotals).sort().forEach(function(name) {",
  "    const s = opTotals[name];",
  "    const kasbon = kasbonMap[name] || 0;",
  "    const grand = s.total + gajiPokok - kasbon;",
  "    const bInfo = bankMap[s.unitCode] || {};",
  "    const isBCA = (bInfo.bank_name || '').toUpperCase().includes('BCA');",
  "    const adminFee = isBCA ? 0 : 2500;",
  "    const netTransfer = grand - adminFee;",
  "    transferRows.push([no++, name, s.unitCode, s.total, gajiPokok, grand, adminFee, netTransfer, bInfo.bank_name || '---', bInfo.bank_account_number || '---', bInfo.bank_account_name || '---']);",
  "    trTotKerja += s.total; trTotPokok += gajiPokok; trTotGrand += grand; trTotFee += adminFee; trTotNet += netTransfer;",
  "  });",
  "  transferRows.push(['', 'TOTAL', '', trTotKerja, trTotPokok, trTotGrand, trTotFee, trTotNet, '', '', '']);",
  "  var wsTransfer = XLSX.utils.aoa_to_sheet(transferRows);",
  "  var trR = XLSX.utils.decode_range(wsTransfer['!ref']);",
  "  for (var ci = 0; ci <= 10; ci++) _xcs(wsTransfer, 0, ci, _xh);",
  "  for (var ri = 1; ri <= trR.e.r; ri++) {",
  "    for (var ci = 0; ci <= 10; ci++) {",
  "      var ref = XLSX.utils.encode_cell({ r: ri, c: ci });",
  "      if (!wsTransfer[ref]) wsTransfer[ref] = { t: 's', v: '' };",
  "      wsTransfer[ref].s = Object.assign({}, wsTransfer[ref].s || {}, { border: _xb });",
  "      if (ci >= 3 && ci <= 7 && wsTransfer[ref].t === 'n') { var _tv = wsTransfer[ref].v; wsTransfer[ref].t = 's'; wsTransfer[ref].v = Math.round(_tv).toLocaleString('id'); delete wsTransfer[ref].w; }",
  "    }",
  "  }",
  "  XLSX.utils.book_append_sheet(wb, wsTransfer, 'TRANSFER');",
  "  const label = batchType === 'mid_month' ? 'Batch16' : 'Batch31';",
  "  XLSX.writeFile(wb, label + '_' + monthYear.replace('-', '') + '.xlsx', { cellStyles: true });",
  "  showToast('Export ' + label + ' berhasil!', 'success');",
  "}"
].join(N);

const toOutput = [
  "  // ExcelJS output — REKAP / SLIP GAJI / TRANSFER with full styling",
  "  if (typeof ExcelJS === 'undefined') { showToast('ExcelJS tidak tersedia'); return; }",
  "  var NF = '#,##0';",
  "  var BDR = { top:{style:'thin'}, bottom:{style:'thin'}, left:{style:'thin'}, right:{style:'thin'} };",
  "  var styleHdr = function(row) { row.eachCell({includeEmpty:true}, function(c) { c.font={bold:true,italic:true}; c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFFF00'}}; c.border=BDR; }); };",
  "  var styleSec = function(row) { row.eachCell({includeEmpty:true}, function(c) { c.font={bold:true}; c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE2EFDA'}}; }); };",
  "  var styleTot = function(row) { row.eachCell({includeEmpty:true}, function(c) { c.font={bold:true}; c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFDBEAFE'}}; }); };",
  "  var styleGrt = function(row) { row.eachCell({includeEmpty:true}, function(c) { c.font={bold:true}; c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFDCFCE7'}}; }); };",
  "  // REKAP sheet",
  "  var wsRekap = wb.addWorksheet('REKAP');",
  "  wsRekap.columns = [{width:14},{width:12},{width:28},{width:8},{width:7},{width:10},{width:10},{width:9},{width:14},{width:10},{width:9},{width:3},{width:14}];",
  "  rekapRows.forEach(function(row, ri) {",
  "    var r2 = row.length > 11 ? row.slice(0,11).concat(['', row[11]]) : row;",
  "    var exRow = wsRekap.addRow(r2);",
  "    if (ri === 0) { styleHdr(exRow); }",
  "    else {",
  "      var c6 = row[6];",
  "      if (c6 === 'SUBTOTAL') { exRow.getCell(7).font={bold:true}; var tc=exRow.getCell(13); tc.font={bold:true}; tc.numFmt=NF; }",
  "      else if (c6 === 'GRAND TOTAL') { styleGrt(exRow); exRow.getCell(13).numFmt=NF; }",
  "      else { exRow.getCell(9).numFmt=NF; exRow.getCell(11).numFmt=NF; exRow.getCell(13).numFmt=NF; }",
  "    }",
  "  });",
  "  // SLIP GAJI sheet",
  "  var _gpok = batchType === 'end_of_month' ? 3100000 : 0;",
  "  var wsSlip = wb.addWorksheet('SLIP GAJI');",
  "  wsSlip.columns = [{width:22},{width:6},{width:28},{width:16},{width:14}];",
  "  Object.keys(unitSheetData).sort().forEach(function(code) {",
  "    var entry = unitSheetData[code];",
  "    var kasbon = kasbonMap[entry.opName] || 0;",
  "    var stkRs = [], kapalRs = [];",
  "    entry.rows.forEach(function(r) {",
  "      if (typeof r[11] === 'number' && r[11] > 0) {",
  "        if (r[9] === 'STK') stkRs.push(r); else kapalRs.push(r);",
  "      }",
  "    });",
  "    var stkTotal = stkRs.reduce(function(s, r) { return s + r[11]; }, 0);",
  "    var kapalTotal = kapalRs.reduce(function(s, r) { return s + r[11]; }, 0);",
  "    var unitTotal = stkTotal + kapalTotal;",
  "    var grandTotal = unitTotal + _gpok - kasbon;",
  "    styleHdr(wsSlip.addRow(['Unit:', code, '', 'Nama Operator:', entry.opName || code]));",
  "    styleHdr(wsSlip.addRow(['Periode:', periodeStr, '', '', '']));",
  "    wsSlip.addRow([]);",
  "    if (stkRs.length > 0) {",
  "      styleSec(wsSlip.addRow(['Pekerjaan Stockpile:', '', '', '', '']));",
  "      stkRs.forEach(function(r, i) { var dr=wsSlip.addRow(['', (i+1)+'.', r[0]+'  ('+r[1]+')', r[7]+' jam', r[11]]); dr.getCell(5).numFmt=NF; });",
  "      var stR=wsSlip.addRow(['', '', 'Subtotal Stockpile:', '', stkTotal]); stR.getCell(3).font={italic:true}; stR.getCell(5).font={italic:true}; stR.getCell(5).numFmt=NF;",
  "      wsSlip.addRow([]);",
  "    }",
  "    if (kapalRs.length > 0) {",
  "      styleSec(wsSlip.addRow(['Pekerjaan Kapal:', '', '', '', '']));",
  "      kapalRs.forEach(function(r, i) { var kade=r[3]?r[3]+'  ':''; var dr=wsSlip.addRow(['', (i+1)+'.', r[2], kade+'('+r[1]+')', r[11]]); dr.getCell(5).numFmt=NF; });",
  "      var ktR=wsSlip.addRow(['', '', 'Subtotal Kapal:', '', kapalTotal]); ktR.getCell(3).font={italic:true}; ktR.getCell(5).font={italic:true}; ktR.getCell(5).numFmt=NF;",
  "      wsSlip.addRow([]);",
  "    }",
  "    var tkR=wsSlip.addRow(['', '', 'Total Kerja:', '', unitTotal]); tkR.getCell(3).font={bold:true}; tkR.getCell(5).numFmt=NF;",
  "    if (_gpok > 0) { var gpR=wsSlip.addRow(['', '', 'Gaji Pokok (Basis):', '', _gpok]); gpR.getCell(3).font={bold:true}; gpR.getCell(5).numFmt=NF; }",
  "    if (kasbon > 0) { var kbR=wsSlip.addRow(['', '', 'Kasbon:', '', -kasbon]); kbR.getCell(3).font={bold:true,color:{argb:'FFDC2626'}}; kbR.getCell(5).numFmt=NF; }",
  "    var totR=wsSlip.addRow(['', '', 'TOTAL BERSIH:', '', grandTotal]); styleTot(totR); totR.getCell(5).numFmt=NF;",
  "    wsSlip.addRow([]);",
  "    wsSlip.addRow([]);",
  "  });",
  "  // TRANSFER sheet",
  "  const gajiPokok = batchType === 'end_of_month' ? 3100000 : 0;",
  "  var wsTransfer = wb.addWorksheet('TRANSFER');",
  "  wsTransfer.columns = [{width:5},{width:18},{width:8},{width:14},{width:14},{width:14},{width:11},{width:14},{width:8},{width:16},{width:20}];",
  "  styleHdr(wsTransfer.addRow(['No','Nama OP','Unit','Total Kerja','Gaji Pokok','Grand Total','Admin Fee','Net Transfer','Bank','No. Rekening','Nama Rekening']));",
  "  let no = 1;",
  "  let trTotKerja = 0, trTotPokok = 0, trTotGrand = 0, trTotFee = 0, trTotNet = 0;",
  "  Object.keys(opTotals).sort().forEach(function(name) {",
  "    const s = opTotals[name];",
  "    const kasbon = kasbonMap[name] || 0;",
  "    const grand = s.total + gajiPokok - kasbon;",
  "    const bInfo = bankMap[s.unitCode] || {};",
  "    const isBCA = (bInfo.bank_name || '').toUpperCase().includes('BCA');",
  "    const adminFee = isBCA ? 0 : 2500;",
  "    const netTransfer = grand - adminFee;",
  "    var dr = wsTransfer.addRow([no++, name, s.unitCode, s.total, gajiPokok, grand, adminFee, netTransfer, bInfo.bank_name||'---', bInfo.bank_account_number||'---', bInfo.bank_account_name||'---']);",
  "    [4,5,6,7,8].forEach(function(ci) { dr.getCell(ci).numFmt=NF; });",
  "    trTotKerja += s.total; trTotPokok += gajiPokok; trTotGrand += grand; trTotFee += adminFee; trTotNet += netTransfer;",
  "  });",
  "  var totTr = wsTransfer.addRow(['', 'TOTAL', '', trTotKerja, trTotPokok, trTotGrand, trTotFee, trTotNet, '', '', '']);",
  "  styleGrt(totTr); [4,5,6,7,8].forEach(function(ci) { totTr.getCell(ci).numFmt=NF; });",
  "  // Download",
  "  const label = batchType === 'mid_month' ? 'Batch16' : 'Batch31';",
  "  const buffer = await wb.xlsx.writeBuffer();",
  "  const blob = new Blob([buffer], {type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});",
  "  const url = URL.createObjectURL(blob);",
  "  const a = document.createElement('a');",
  "  a.href = url; a.download = label + '_' + monthYear.replace('-', '') + '.xlsx';",
  "  document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);",
  "  showToast('Export ' + label + ' berhasil!', 'success');",
  "}"
].join(N);

replaceExact(fromOutput, toOutput, 'PATCH 3: Replace SheetJS output section with ExcelJS');

if (fails > 0) { console.error('ABORT: ' + fails + ' patch(es) failed, file NOT written'); process.exit(1); }
fs.writeFileSync(FILE, src);
console.log('DONE: index.html written — 3 patches applied');
